services:
  app:
    image: devopsdockeruh/simple-web-service
    container_name: simple-web-service
    command: server
    volumes:
      - ./logs/text.log:/usr/src/app/text.log
    ports:
      - "8080:8080"